name: CI - Restaurant System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 15

      - name: Run Prisma Migrations
        run: docker compose exec -T api npx prisma migrate deploy

      - name: Run tests
        run: docker compose exec -T api npm test

      - name: Stop containers
        run: docker compose down